### ISSUE TITLE
Schema creation options.

### ISSUE THREAD

**Issue by chaddm** [chaddm/schemafy#5]
Right now, when creating the schema there are few baked in options that should probably be extracted out and made optional.

* You can pass in an XML-like option (i.e. array of arrays) and if the schema isn't expecting an array, but there is an array with one item, the one item is extracted and used.  Useful, but may side-effect for malformed data.
* Logging is externalized, but not exposed as an inject-able dependency.  Should be able to set the logger.

**Comment by ebiven** [comment]
I think we originally added the XML-like functionality to deal with a very specific use case we had. I can't think of a good reason to leave it in and agree that it's a side-effect waiting to happen.

**Comment by chaddm** [comment]
Good point.  Let's rip it out.

**Comment by chaddm** [comment]
I am thinking that XML stuff should be ripped out and we just throw errors.  So, going to work on that.

**Comment by chaddm** [comment]
Per our discussions, I'm going to make coercion the default.
